package:
  name: sixs_json
  version: 1.0.0

source:
  path: .

requirements:
  build:
    - cmake
    - make
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}              # [unix]
    - {{ compiler('cxx') }}            # [unix]
    - {{ compiler('m2w64_c') }}        # [win]
    - posix  # [win]
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - m2w64-gcc-libgfortran  # [win]
    - python

test:
  imports:
    - sixs_json
  commands:
    - pip check
  requires:
    - pip
  files:
  - test_params.txt

about:
  home: https://github.com/raphidoc/sixs_json
  license: MIT
  summary: 'The 6S atmospheric radiative transfer model modified with JSON output'

extra:
  recipe-maintainers:
    - raphidoc