{% set name = "sixs_json" %}
{% set version = "1.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/raphidoc/sixs_json/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 987d1b193c6a676cc8729ca61a557f1e511651207eabecb58ba6bf4430a99f22

build:
  number: 0

requirements:
  build:
    - cmake
    - make
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('c') }}              # [unix]
    - m2w64-gcc-fortran [win]
    - m2w64-gcc [win]
    - posix [win]
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - m2w64-gcc-libgfortran  # [win]
    - python

test:
  imports:
    - sixs_json
  commands:
    - pip check
  requires:
    - pip
  files:
    - test_params.txt

about:
  home: https://github.com/raphidoc/sixs_json
  license: MIT
  summary: 'The 6S atmospheric radiative transfer model modified with JSON output'

extra:
  recipe-maintainers:
    - raphidoc
